Numpy

In [1]:
import numpy as np

In [2]:
ones_arr=np.ones((2,3,4))
ones_arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [3]:
x=np.ones((3,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
x.shape

(3, 4)

In [6]:
y=np.random.random((3,4))
y

array([[0.1102948 , 0.60299806, 0.98261325, 0.76122335],
       [0.04048493, 0.84434574, 0.99976998, 0.16793345],
       [0.3917529 , 0.12245541, 0.93331338, 0.61153855]])

In [7]:
y.shape

(3, 4)

In [8]:
x+y

array([[1.1102948 , 1.60299806, 1.98261325, 1.76122335],
       [1.04048493, 1.84434574, 1.99976998, 1.16793345],
       [1.3917529 , 1.12245541, 1.93331338, 1.61153855]])

In [10]:
z=np.random.random((2,3,4))
z

array([[[0.53149147, 0.94304531, 0.02337315, 0.27777349],
        [0.86910251, 0.99961832, 0.31891918, 0.61563002],
        [0.35627922, 0.31967715, 0.65700856, 0.42146723]],

       [[0.99700094, 0.76793497, 0.72651857, 0.65973349],
        [0.72829335, 0.15144571, 0.98896895, 0.67183605],
        [0.21703581, 0.24916802, 0.37968183, 0.00808223]]])

In [11]:
z.shape

(2, 3, 4)

In [12]:
x+z

array([[[1.53149147, 1.94304531, 1.02337315, 1.27777349],
        [1.86910251, 1.99961832, 1.31891918, 1.61563002],
        [1.35627922, 1.31967715, 1.65700856, 1.42146723]],

       [[1.99700094, 1.76793497, 1.72651857, 1.65973349],
        [1.72829335, 1.15144571, 1.98896895, 1.67183605],
        [1.21703581, 1.24916802, 1.37968183, 1.00808223]]])

In [13]:
ar1=np.array([[20,30,40],[30,40,60]])
ar1

array([[20, 30, 40],
       [30, 40, 60]])

In [14]:
ar1.shape

(2, 3)

In [15]:
x=np.array([10])
x

array([10])

In [16]:
x.shape

(1,)

In [17]:
ar1+x

array([[30, 40, 50],
       [40, 50, 70]])

In [19]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([10,20,30])

In [20]:
np.add(x,y)

array([[11, 22, 33],
       [14, 25, 36]])

In [22]:
d=np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
d=np.arange(9).reshape((3,3))
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
d[1,2]

5

In [ ]:
d[:][-1]

array([2, 5, 8])

In [42]:
d[1:,1:]

array([[4, 5],
       [7, 8]])

In [ ]:
d[1:,2:]

array([[3],
       [6]])

In [52]:
d[1:,:1]

array([[3],
       [6]])

In [57]:
d[d>2]

array([3, 4, 5, 6, 7, 8])

In [59]:
ar1=np.array([1,3,4])
ar2=np.array([2,4,5])

In [60]:
ar1*ar2

array([ 2, 12, 20])

In [63]:
np.dot(ar1,ar2)

34

In [ ]:
np.matmul(ar1,ar2)

34

In [64]:
a=np.array([[20,30],[2,4]])

In [67]:
c=np.array([10,50])

In [68]:
np.linalg.solve(a,c)

array([-73.,  49.])

In [69]:
np.random.rand(2,2,2)

array([[[0.56530441, 0.35244167],
        [0.49045107, 0.09889764]],

       [[0.29683794, 0.09779547],
        [0.62277675, 0.81922612]]])

In [162]:
np.random.randint(5,size=(4,4))

array([[0, 3, 3, 4],
       [1, 0, 4, 2],
       [1, 2, 3, 1],
       [1, 3, 4, 3]])

In [240]:
np.random.choice(4,4,4)

array([3, 1, 2, 2])